sonar.projectKey=devops-portfolio
sonar.projectName=DevOps Portfolio API
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=app/tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml

# Source / analysis exclusions
sonar.exclusions=**/tests/**,**/.venv/**,**/__pycache__/**,**/*.sql,**/migrations/**
sonar.test.exclusions=**/tests/**

# Coverage exclusions (non-testable / bootstrap code)
sonar.coverage.exclusions=**/tests/**,app/__init__.py,scripts/**,**/db.py

# Duplication exclusions
sonar.cpd.exclusions=**/tests/**
